name: Deploy
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      deploy-namespace:
        required: true
        type: string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 下载部署文件
        uses: actions/download-artifact@v4
        with:
          name: build-outputs-kubernetes
      - name: Download Deploy Script
        run: wget -O deploy.sh https://gist.githubusercontent.com/Mystery00/6842ae8d787c47361ee83406e0d73f03/raw/985d527e8310057eba71f29afdafdd1f1b059a3f/kube-apply.sh
      - name: 替换文本
        run: |
          if [ -f template/config.yaml ];then
            sed -i "s/{{PROJECT_NAME}}/${{ inputs.project-name }}/g" template/config.yaml
            mv template/config.yaml kustomization.yaml
          fi
          sed -i "s/{{PROJECT_NAME}}/${{ inputs.project-name }}/g" outputs/kubernetes/deployment.yaml
          mv outputs/kubernetes/deployment.yaml deployment.yaml
      - name: 部署到集群
        run: bash deploy.sh "${{ inputs.project-name }}" "${{ inputs.deploy-namespace }}"