name: Build & Push Docker Image
on:
  workflow_call:
    inputs:
      docker-image-tag:
        required: true
        type: string
    secrets:
      REGISTRY_URL:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Download Output Files
        uses: actions/download-artifact@v4
        with:
          name: build-outputs-docker
      - run: |
          ls -la
          tree
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: build-outputs-docker/outputs/docker
          file: build-outputs-docker/outputs/docker/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/${{ inputs.docker-image-tag }}