name: Build SpringBoot Application
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      artifact-path:
        required: true
        type: string
      docker-dir-path:
        required: true
        type: string
      docker-image-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      image-pull-secrets:
        required: true
        type: string
    outputs:
      docker_image_tag: ${{ steps.version.outputs.docker_image_tag }}
jobs:
  build_springboot:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v4
      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
      - run: chmod a+x gradlew
      - name: Build Application
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build -x test
      - name: Copy Artifact
        run: |
          mkdir -p outputs/docker
          mkdir -p outputs/kubernetes
          cp "${{ inputs.artifact-path }}" "outputs/docker/"
          cp -r "${{ inputs.docker-dir-path }}/*" "outputs/docker/"
      - name: Generate Version
        id: version
        run: |
          version_name=`git rev-parse --short=4 HEAD`
          date=`date "+%Y%m%d"`
          docker_image_tag="${{ inputs.docker-image-name }}:${date}-${version_name}"
          sed "s/{{PROJECT_NAME}}/${{ inputs.project-name }}/g;s?{{DOCKER_IMAGE}}?$docker_image_tag?g;s/{{IMAGE_PULL_SECRETS}}/${{ inputs.image-pull-secrets}}/g" template/deployment.yaml > outputs/kubernetes/deployment.yaml
          echo "docker_image_tag=$docker_image_tag" >> $GITHUB_OUTPUT
      - name: Upload Output Docker Files
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-docker
          path: |
            outputs/docker/
      - name: Upload Output Kubernetes Files
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-kubernetes
          path: |
            outputs/kubernetes/